/**
 * AES User Story & Journey Types
 *
 * Captures how users actually experience each feature.
 * Three layers:
 *   1. User Story — classic product form (as a / i want / so that)
 *   2. Usage Narrative — what the user actually does step by step
 *   3. Journey State — the flow model with preconditions, main/alt/failure flows
 *
 * Two sources of truth:
 *   - Inventor story: what the founder wants the experience to feel like
 *   - Research story: what real users in similar products tend to expect
 *
 * Rule: inventor story sets product intent, research adds realism,
 *       research never overwrites the invention.
 */

// ─── User Story ──────────────────────────────────────────────────────────────

export interface UserStory {
  story_id: string;
  feature_id: string;
  as_a: string;
  i_want: string;
  so_that: string;
  source: StorySource;
  priority: "critical" | "high" | "medium" | "low";
  acceptance_criteria_ids: string[];
}

export type StorySource =
  | "inventor"          // founder-specified
  | "research_derived"  // from market/user research
  | "merged"            // combined inventor + research
  | "system_inferred";  // generated by decomposer

// ─── Usage Narrative ─────────────────────────────────────────────────────────

export interface UsageNarrative {
  narrative_id: string;
  feature_id: string;
  /** What triggers this flow */
  trigger: string;
  /** First thing the user does */
  first_action: string;
  /** Information the user needs to see */
  needed_information: string[];
  /** The key decision or action point */
  decision_point: string;
  /** What could go wrong */
  what_could_go_wrong: string[];
  /** What happens after the main action */
  next_step: string[];
  /** Trust moments — where user needs reassurance */
  trust_moments: string[];
  /** Where users typically drop off */
  drop_off_risks: string[];
  source: StorySource;
}

// ─── Journey State ───────────────────────────────────────────────────────────

export interface JourneyState {
  journey_id: string;
  feature_id: string;
  /** What must be true before this journey starts */
  precondition: string[];
  /** Happy path steps */
  main_flow: string[];
  /** Alternative paths (e.g. request more info before approving) */
  alternate_flows: AlternateFlow[];
  /** Failure paths */
  failure_flows: FailureFlow[];
  /** What's true when the journey completes successfully */
  completion_state: string[];
  source: StorySource;
}

export interface AlternateFlow {
  name: string;
  trigger: string;
  steps: string[];
}

export interface FailureFlow {
  name: string;
  trigger: string;
  user_sees: string;
  recovery_action: string;
}

// ─── Story Confidence ────────────────────────────────────────────────────────

export interface StoryConfidence {
  inventor_provided: boolean;
  research_derived: boolean;
  merged: boolean;
  confidence: number;
  /** If research conflicted with inventor, what was rejected */
  rejected_research: string[];
  /** If inventor provided guidance that overrode research */
  inventor_overrides: string[];
}

// ─── Research Classification ─────────────────────────────────────────────────

export type ResearchClassification = "BORROW" | "AVOID" | "EXPECT" | "REJECTED";

export interface ClassifiedResearchFinding {
  finding_id: string;
  feature_id: string;
  description: string;
  classification: ResearchClassification;
  reason: string;
  /** Who classified it — "user" or "system" */
  classified_by: "user" | "system";
  /** Original research source */
  research_source: string;
}

// ─── Founder Intent ──────────────────────────────────────────────────────────

export interface FounderIntent {
  app_id: string;
  /** The founder's description of the desired experience */
  experience_description: string;
  /** Key phrases that define the product feel */
  feel_keywords: string[];
  /** Explicit "do not" from the founder */
  anti_goals: string[];
  /** Strategic bets the founder is making */
  strategic_bets: string[];
  /** Provided at intake time */
  provided_at: string;
}

// ─── Synthesis Decision ──────────────────────────────────────────────────────

export interface SynthesisDecision {
  decision_id: string;
  feature_id: string;
  founder_intent: string;
  research_expectation: string[];
  synthesis: string[];
  rejected_research: string[];
  decision_rationale: string;
}

// ─── Feature User Context (everything stored per feature) ────────────────────

export interface FeatureUserContext {
  feature_id: string;
  app_id: string;
  user_stories: UserStory[];
  usage_narratives: UsageNarrative[];
  journey_states: JourneyState[];
  story_confidence: StoryConfidence;
  classified_findings: ClassifiedResearchFinding[];
  synthesis_decisions: SynthesisDecision[];
  created_at: string;
  updated_at: string;
}
