/**
 * AES Phase 1 — Real Build Test
 *
 * This is the first test where AES produces REAL code, runs REAL tests,
 * and validates REAL output. No simulations.
 *
 * Target: A todo API with CRUD endpoints
 * What happens:
 *   1. Bridge compiled with system context
 *   2. Code generator writes actual TypeScript files to disk
 *   3. Jest runs actual tests against the generated code
 *   4. Validator checks the real diff and test results
 *   5. Artifacts recorded in the registry
 *
 * The "builder" here is a deterministic code generator, not Claude.
 * This proves the pipeline works. Swapping in Claude as the builder
 * is a config change, not an architecture change.
 */

import * as fs from "fs";
import * as path from "path";
import { execSync } from "child_process";
import { ArtifactRegistry } from "../src/registry/registry";
import { InMemoryStorage } from "../src/registry/storage";
import { BridgeCompiler } from "../src/bridge/bridge-compiler";
import { generateArtifactId } from "../src/registry/id-generator";
import type {
  Bridge,
  Build,
  DiffArtifact,
  TestRun,
  ValidatorRun,
  GraphSnapshot,
  ChangedFile,
} from "../src/types/artifacts";

// ─── Workspace Setup ─────────────────────────────────────────────────────────

const WORKSPACE = path.resolve(__dirname, "phase1-workspace");
const SRC_DIR = path.join(WORKSPACE, "src");
const TEST_DIR = path.join(WORKSPACE, "__tests__");

function cleanWorkspace() {
  if (fs.existsSync(SRC_DIR)) fs.rmSync(SRC_DIR, { recursive: true });
  if (fs.existsSync(TEST_DIR)) fs.rmSync(TEST_DIR, { recursive: true });
  fs.mkdirSync(SRC_DIR, { recursive: true });
  fs.mkdirSync(TEST_DIR, { recursive: true });
}

// fileHash available if needed for content-addressable storage
// function fileHash(content: string): string {
//   return crypto.createHash("sha256").update(content).digest("hex").slice(0, 16);
// }

// ─── The Builder: Writes Real Code from Bridge ───────────────────────────────

interface BuildOutput {
  files_written: Array<{ path: string; content: string }>;
  test_files_written: Array<{ path: string; content: string }>;
}

/**
 * Deterministic builder that reads a bridge and writes real TypeScript.
 * This replaces Claude for testing purposes.
 */
function buildFromBridge(bridge: Bridge, workspace: string): BuildOutput {
  const srcDir = path.join(workspace, "src");
  const testDir = path.join(workspace, "__tests__");

  const files: BuildOutput["files_written"] = [];
  const testFiles: BuildOutput["test_files_written"] = [];

  // Read the bridge intent and generate code
  const intent = bridge.intent.toLowerCase();

  if (intent.includes("todo")) {
    // Generate todo model
    const modelContent = `/**
 * Todo Model — Generated by AES Builder
 * Bridge: ${bridge.bridge_id}
 * Feature: ${bridge.feature_id}
 */

export interface Todo {
  id: string;
  title: string;
  completed: boolean;
  created_at: string;
  updated_at: string;
}

export interface CreateTodoInput {
  title: string;
}

export interface UpdateTodoInput {
  title?: string;
  completed?: boolean;
}
`;

    const modelPath = path.join(srcDir, "todo-model.ts");
    fs.writeFileSync(modelPath, modelContent);
    files.push({ path: "src/todo-model.ts", content: modelContent });

    // Generate todo service
    const serviceContent = `/**
 * Todo Service — Generated by AES Builder
 * Bridge: ${bridge.bridge_id}
 */

import type { Todo, CreateTodoInput, UpdateTodoInput } from "./todo-model";

let nextId = 1;
const store = new Map<string, Todo>();

export function createTodo(input: CreateTodoInput): Todo {
  const now = new Date().toISOString();
  const todo: Todo = {
    id: String(nextId++),
    title: input.title.trim(),
    completed: false,
    created_at: now,
    updated_at: now,
  };

  if (!todo.title) {
    throw new Error("Title is required");
  }

  store.set(todo.id, todo);
  return todo;
}

export function getTodo(id: string): Todo | undefined {
  return store.get(id);
}

export function listTodos(): Todo[] {
  return Array.from(store.values());
}

export function updateTodo(id: string, input: UpdateTodoInput): Todo {
  const todo = store.get(id);
  if (!todo) throw new Error(\`Todo \${id} not found\`);

  const updated: Todo = {
    ...todo,
    title: input.title !== undefined ? input.title.trim() : todo.title,
    completed: input.completed !== undefined ? input.completed : todo.completed,
    updated_at: new Date().toISOString(),
  };

  store.set(id, updated);
  return updated;
}

export function deleteTodo(id: string): boolean {
  return store.delete(id);
}

export function clearStore(): void {
  store.clear();
  nextId = 1;
}
`;

    const servicePath = path.join(srcDir, "todo-service.ts");
    fs.writeFileSync(servicePath, serviceContent);
    files.push({ path: "src/todo-service.ts", content: serviceContent });

    // Generate real tests
    const testContent = `/**
 * Todo Service Tests — Generated by AES Builder
 * Bridge: ${bridge.bridge_id}
 */

import {
  createTodo,
  getTodo,
  listTodos,
  updateTodo,
  deleteTodo,
  clearStore,
} from "../src/todo-service";

beforeEach(() => {
  clearStore();
});

describe("Todo CRUD", () => {
  test("create a todo", () => {
    const todo = createTodo({ title: "Buy milk" });
    expect(todo.id).toBeDefined();
    expect(todo.title).toBe("Buy milk");
    expect(todo.completed).toBe(false);
    expect(todo.created_at).toBeDefined();
  });

  test("get a todo by id", () => {
    const created = createTodo({ title: "Walk dog" });
    const found = getTodo(created.id);
    expect(found).toBeDefined();
    expect(found!.title).toBe("Walk dog");
  });

  test("list all todos", () => {
    createTodo({ title: "First" });
    createTodo({ title: "Second" });
    const all = listTodos();
    expect(all).toHaveLength(2);
  });

  test("update a todo", () => {
    const todo = createTodo({ title: "Original" });
    const updated = updateTodo(todo.id, { title: "Updated", completed: true });
    expect(updated.title).toBe("Updated");
    expect(updated.completed).toBe(true);
  });

  test("delete a todo", () => {
    const todo = createTodo({ title: "Delete me" });
    expect(deleteTodo(todo.id)).toBe(true);
    expect(getTodo(todo.id)).toBeUndefined();
  });

  test("create rejects empty title", () => {
    expect(() => createTodo({ title: "" })).toThrow("Title is required");
  });

  test("update rejects missing todo", () => {
    expect(() => updateTodo("999", { title: "Nope" })).toThrow("not found");
  });

  test("delete returns false for missing todo", () => {
    expect(deleteTodo("999")).toBe(false);
  });
});
`;

    const testPath = path.join(testDir, "todo-service.test.ts");
    fs.writeFileSync(testPath, testContent);
    testFiles.push({ path: "__tests__/todo-service.test.ts", content: testContent });
  }

  return { files_written: files, test_files_written: testFiles };
}

// ─── Real Test Runner ────────────────────────────────────────────────────────

interface RealTestResult {
  passed: number;
  failed: number;
  total: number;
  output: string;
  success: boolean;
}

function runRealTests(workspace: string): RealTestResult {
  try {
    // Use the parent project's jest config but run in the workspace
    const output = execSync(
      `npx jest --roots "${workspace}" --config '${JSON.stringify({
        preset: "ts-jest",
        testEnvironment: "node",
        roots: [workspace],
        modulePaths: [workspace],
      })}' --no-cache --runInBand 2>&1`,
      {
        cwd: path.resolve(workspace, ".."),
        timeout: 30000,
        encoding: "utf-8",
      }
    );

    // Parse results from output
    const passMatch = output.match(/Tests:\s+(\d+) passed/);
    const failMatch = output.match(/(\d+) failed/);
    const totalMatch = output.match(/(\d+) total/);

    return {
      passed: passMatch ? parseInt(passMatch[1]!) : 0,
      failed: failMatch ? parseInt(failMatch[1]!) : 0,
      total: totalMatch ? parseInt(totalMatch[1]!) : 0,
      output,
      success: !output.includes("FAIL"),
    };
  } catch (error: any) {
    const output = error.stdout?.toString() ?? error.message;
    const passMatch = output.match(/Tests:\s+(\d+) passed/);
    const failMatch = output.match(/(\d+) failed/);

    return {
      passed: passMatch ? parseInt(passMatch[1]!) : 0,
      failed: failMatch ? parseInt(failMatch[1]!) : 0,
      total: (passMatch ? parseInt(passMatch[1]!) : 0) + (failMatch ? parseInt(failMatch[1]!) : 0),
      output,
      success: false,
    };
  }
}

// ─── Real Diff Capture ───────────────────────────────────────────────────────

function captureRealDiff(buildOutput: BuildOutput): {
  changed_files: ChangedFile[];
  total_lines_added: number;
} {
  const changed_files: ChangedFile[] = [];
  let total_lines_added = 0;

  for (const file of [...buildOutput.files_written, ...buildOutput.test_files_written]) {
    const lines = file.content.split("\n").length;
    total_lines_added += lines;
    changed_files.push({
      path: file.path,
      change_type: "added",
      lines_added: lines,
      lines_removed: 0,
      in_write_scope: true,
    });
  }

  return { changed_files, total_lines_added };
}

// ─── Real Validator ──────────────────────────────────────────────────────────

interface RealValidationResult {
  passed: boolean;
  violations: string[];
  concerns: string[];
}

function validateRealBuild(
  bridge: Bridge,
  buildOutput: BuildOutput,
  testResult: RealTestResult,
  diffResult: ReturnType<typeof captureRealDiff>,
): RealValidationResult {
  const violations: string[] = [];
  const concerns: string[] = [];

  // Check: all files within write_scope
  const writeScope = bridge.write_scope.paths;
  for (const file of diffResult.changed_files) {
    const inScope = writeScope.some(scope => file.path.startsWith(scope));
    if (!inScope) {
      violations.push(`File ${file.path} is outside write_scope ${writeScope.join(", ")}`);
    }
  }

  // Check: tests pass
  if (!testResult.success) {
    violations.push(`Tests failed: ${testResult.failed} of ${testResult.total}`);
  }

  // Check: test count meets expectations
  if (testResult.total < (bridge.test_cases?.length ?? 1)) {
    concerns.push(`Only ${testResult.total} tests ran, bridge expected ${bridge.test_cases?.length ?? "unknown"}`);
  }

  // Check: files were actually generated
  if (buildOutput.files_written.length === 0) {
    violations.push("No source files were generated");
  }

  // Check: test files were generated
  if (buildOutput.test_files_written.length === 0) {
    violations.push("No test files were generated");
  }

  // Check: acceptance criteria coverage (basic)
  for (const criterion of bridge.acceptance_criteria) {
    if (criterion.mandatory) {
      // Check that at least one test references this criterion's intent
      const criterionKeywords = criterion.description.toLowerCase().split(/\s+/);
      const hasTest = testResult.output.toLowerCase().includes(criterionKeywords[0]!) ||
        buildOutput.test_files_written.some(f =>
          criterionKeywords.some(kw => f.content.toLowerCase().includes(kw))
        );
      if (!hasTest) {
        concerns.push(`No test appears to cover: ${criterion.description}`);
      }
    }
  }

  return {
    passed: violations.length === 0,
    violations,
    concerns,
  };
}

// ─── The Test ────────────────────────────────────────────────────────────────

describe("Phase 1 — Real Build End-to-End", () => {
  let registry: ArtifactRegistry;

  beforeAll(() => {
    registry = new ArtifactRegistry(new InMemoryStorage());
    cleanWorkspace();
  });

  afterAll(() => {
    // Clean up generated files
    cleanWorkspace();
  });

  test("full pipeline: bridge → real code → real tests → real validation → artifacts", async () => {
    const now = new Date().toISOString();

    // 1. Create a graph snapshot (minimal)
    const snapshot: GraphSnapshot = {
      graph_snapshot_id: generateArtifactId("graph_snapshot"),
      feature_id: "FEAT-TODO-001",
      captured_at: now,
      graph_truth_hash: "hash-todo-test",
      referenced_nodes: [],
      referenced_edges: [],
      critical_domain_nodes: [],
      artifact_refs: [
        { artifact_type: "graph_snapshot", artifact_id: "self", role: "graph_snapshot_source" },
      ],
    };
    await registry.write("graph_snapshot", snapshot);

    // 2. Compile a bridge with real system context
    const compiler = new BridgeCompiler(registry);
    const bridgeRecord = await compiler.compile({
      build_id: generateArtifactId("build"),
      feature_id: "FEAT-TODO-001",
      graph_snapshot: snapshot,
      intent: "Build a todo CRUD service with create, read, update, delete operations",
      scope: { paths: ["src/", "__tests__/"] },
      read_scope: { paths: ["src/", "__tests__/"] },
      write_scope: { paths: ["src/", "__tests__/"] },
      constraints: [
        "Use TypeScript",
        "In-memory storage (no external DB for this feature)",
        "Validate inputs — reject empty titles",
        "All timestamps in ISO 8601",
      ],
      patterns: ["repository-pattern", "service-layer"],
      anti_patterns: ["no-global-mutable-state-without-reset"],
      data_model: {
        feature_type: "backend_platform",
        entities: {
          Todo: {
            fields: ["id", "title", "completed", "created_at", "updated_at"],
            operations: ["CREATE", "READ", "UPDATE", "DELETE"],
          },
        },
      },
      acceptance_criteria: [
        { id: "ac-1", description: "Create a todo with a title", type: "functional", mandatory: true },
        { id: "ac-2", description: "Get a todo by ID", type: "functional", mandatory: true },
        { id: "ac-3", description: "List all todos", type: "functional", mandatory: true },
        { id: "ac-4", description: "Update a todo title and completion", type: "functional", mandatory: true },
        { id: "ac-5", description: "Delete a todo", type: "functional", mandatory: true },
        { id: "ac-6", description: "Reject empty title on create", type: "boundary", mandatory: true },
      ],
      test_cases: [
        { id: "tc-1", description: "Create todo", type: "unit", linked_criterion_id: "ac-1", mandatory: true },
        { id: "tc-2", description: "Get todo by ID", type: "unit", linked_criterion_id: "ac-2", mandatory: true },
        { id: "tc-3", description: "List todos", type: "unit", linked_criterion_id: "ac-3", mandatory: true },
        { id: "tc-4", description: "Update todo", type: "unit", linked_criterion_id: "ac-4", mandatory: true },
        { id: "tc-5", description: "Delete todo", type: "unit", linked_criterion_id: "ac-5", mandatory: true },
        { id: "tc-6", description: "Reject empty title", type: "boundary", linked_criterion_id: "ac-6", mandatory: true },
      ],
      confidence_breakdown: {
        graph_coverage: 0.8,
        pattern_strength: 0.7,
        rule_consistency: 0.9,
        evidence_level: 0.6,
      },
      artifact_refs: [
        { artifact_type: "graph_snapshot", artifact_id: snapshot.graph_snapshot_id, role: "graph_snapshot_source" },
      ],
    });

    const bridge = bridgeRecord.payload;
    expect(bridge.status).toBe("DRAFT");
    expect(bridge.data_model).toHaveProperty("system_context");

    console.log(`Bridge compiled: ${bridge.bridge_id}`);
    console.log(`System context injected: ${Object.keys((bridge.data_model as any).system_context).join(", ")}`);

    // 3. REAL BUILD — Write actual TypeScript files to disk
    const buildOutput = buildFromBridge(bridge, WORKSPACE);

    expect(buildOutput.files_written.length).toBeGreaterThan(0);
    expect(buildOutput.test_files_written.length).toBeGreaterThan(0);

    // Verify files exist on disk
    for (const file of buildOutput.files_written) {
      const fullPath = path.join(WORKSPACE, file.path);
      expect(fs.existsSync(fullPath)).toBe(true);
    }

    console.log(`Files written: ${buildOutput.files_written.map(f => f.path).join(", ")}`);
    console.log(`Test files written: ${buildOutput.test_files_written.map(f => f.path).join(", ")}`);

    // 4. REAL TESTS — Run jest against the generated code
    const testResult = runRealTests(WORKSPACE);

    console.log(`Tests: ${testResult.passed} passed, ${testResult.failed} failed, ${testResult.total} total`);
    expect(testResult.success).toBe(true);
    expect(testResult.passed).toBeGreaterThanOrEqual(6);
    expect(testResult.failed).toBe(0);

    // 5. REAL DIFF — Capture what changed
    const diffResult = captureRealDiff(buildOutput);

    expect(diffResult.changed_files.length).toBe(3); // model + service + test
    expect(diffResult.total_lines_added).toBeGreaterThan(50);

    // 6. REAL VALIDATION — Check against bridge constraints
    const validationResult = validateRealBuild(bridge, buildOutput, testResult, diffResult);

    console.log(`Validation: ${validationResult.passed ? "PASSED" : "FAILED"}`);
    if (validationResult.violations.length > 0) {
      console.log(`Violations: ${validationResult.violations.join("; ")}`);
    }
    if (validationResult.concerns.length > 0) {
      console.log(`Concerns: ${validationResult.concerns.join("; ")}`);
    }

    expect(validationResult.passed).toBe(true);
    expect(validationResult.violations).toHaveLength(0);

    // 7. Record all artifacts in the registry
    // Build record
    await registry.write("build", {
      build_id: bridge.build_id,
      bridge_id: bridge.bridge_id,
      feature_id: bridge.feature_id,
      status: "PASSED",
      blocked_reasons: [],
      queued_at: now,
      authorized_at: now,
      started_at: now,
      ended_at: new Date().toISOString(),
      builder_session_id: "phase1-deterministic-builder",
      artifact_refs: [
        { artifact_type: "bridge", artifact_id: bridge.bridge_id, role: "constraint_source" },
      ],
    } as Build);

    // Diff record
    const diffRecord = await registry.write("diff_artifact", {
      diff_artifact_id: generateArtifactId("diff_artifact"),
      build_id: bridge.build_id,
      bridge_id: bridge.bridge_id,
      feature_id: bridge.feature_id,
      captured_at: new Date().toISOString(),
      changed_files: diffResult.changed_files,
      path_violations: [],
      blob_ref: null,
      artifact_refs: [
        { artifact_type: "build", artifact_id: bridge.build_id, role: "diff_source" },
      ],
    } as DiffArtifact);

    // Test run record
    const testRunRecord = await registry.write("test_run", {
      test_run_id: generateArtifactId("test_run"),
      build_id: bridge.build_id,
      bridge_id: bridge.bridge_id,
      feature_id: bridge.feature_id,
      executed_at: new Date().toISOString(),
      test_cases_run: testResult.total,
      passed: testResult.passed,
      failed: testResult.failed,
      skipped: 0,
      status: testResult.success ? "PASS" : "FAIL",
      failure_details: [],
      blob_ref: null,
      artifact_refs: [
        { artifact_type: "build", artifact_id: bridge.build_id, role: "test_source" },
      ],
    } as TestRun);

    // Validator run record
    await registry.write("validator_run", {
      validator_id: "v-phase1-real",
      validator_run_id: generateArtifactId("validator_run"),
      build_id: bridge.build_id,
      bridge_id: bridge.bridge_id,
      validated_at: new Date().toISOString(),
      status: validationResult.passed ? "PASS" : "FAIL",
      evidence: [
        { evidence_type: "test_run", description: `${testResult.passed} tests passed`, artifact_ref: { artifact_type: "test_run", artifact_id: testRunRecord.payload.test_run_id, role: "test_source" } },
        { evidence_type: "diff", description: `${diffResult.changed_files.length} files, ${diffResult.total_lines_added} lines added`, artifact_ref: { artifact_type: "diff_artifact", artifact_id: diffRecord.payload.diff_artifact_id, role: "diff_source" } },
      ],
      violations: validationResult.violations.map(v => ({
        rule: "bridge_constraint",
        severity: "HARD" as const,
        description: v,
      })),
      missing: [],
      concerns: validationResult.concerns,
      confidence: validationResult.passed ? 0.95 : 0.2,
      artifact_refs: [
        { artifact_type: "build", artifact_id: bridge.build_id, role: "validation_evidence" },
      ],
    } as ValidatorRun);

    // 8. Verify full artifact trail
    const allBuildArtifacts = await registry.byBuild(bridge.build_id);
    const artifactTypes = new Set(allBuildArtifacts.map(a => a.artifact_type));

    expect(artifactTypes.has("diff_artifact")).toBe(true);
    expect(artifactTypes.has("test_run")).toBe(true);
    expect(artifactTypes.has("validator_run")).toBe(true);

    console.log(`\n── Phase 1 Complete ──`);
    console.log(`Bridge: ${bridge.bridge_id}`);
    console.log(`Build: ${bridge.build_id} — PASSED`);
    console.log(`Code: ${buildOutput.files_written.length} source files, ${buildOutput.test_files_written.length} test files`);
    console.log(`Tests: ${testResult.passed} passed, ${testResult.failed} failed`);
    console.log(`Validation: ${validationResult.passed ? "PASSED" : "FAILED"}, ${validationResult.concerns.length} concerns`);
    console.log(`Artifacts: ${allBuildArtifacts.length} total in registry`);
    console.log(`Lines of real code: ${diffResult.total_lines_added}`);
  });
});
